// apps/web/components/Home/footer.tsx
export function Footer() {
  return (
    <footer className=" bg-blackBg py-44">
      <div className="mx-auto w-full max-w-screen-xl">
        <div className="grid grid-cols-1 gap-8 px-4 py-6 md:grid-cols-3 lg:py-8">
          <div>
            <h2 className="mb-8 text-5xl font-medium text-white">Logo</h2>
            <ul className="text-2xl font-normal text-[#8E8E8E]">
              <li className="mb-4">
                <a href="#" className=" hover:underline">
                  Address{" "}
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h2 className="text-[32px] font-semibold text-[#F6F6F6] ">
              Quick links
            </h2>
            <ul className="grid grid-cols-2 gap-y-[26px] text-2xl font-normal text-[#8E8E8E] ">
              <li className="">
                <a href="#" className="hover:underline">
                  Home
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  Privacy policy
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  About us
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  Cookie policy
                </a>
              </li>
              <li className="md:col-span-2">
                <a href="#" className="hover:underline">
                  Token
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  Blogs
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h2 className="mb-12 text-lg font-semibold text-[#F6F6F6]">
              Join our community
            </h2>
            <ul className="grid grid-cols-4 gap-y-14">
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Linkedin.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Discord.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Twitter.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Instagram.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Youtube.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Twitch.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Tik tok.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
              <li className="">
                <a href="#" className="hover:underline">
                  <img
                    src="/img/Facebook.png"
                    alt=""
                    className="h-[60px] w-[60px] object-cover"
                  />
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  );
}

// apps/webSvelte/src/routes/Footer.svelte
<footer class=" bg-paper-950">
	<div class="mx-auto w-full max-w-screen-xl">
		<div class="grid grid-cols-1 gap-8 px-4 py-6 md:grid-cols-3 lg:py-8">
			<div>
				<h2 class="mb-8 text-5xl font-medium text-white">Logo</h2>
				<ul class="text-2xl font-normal text-paper-400">
					<li class="mb-4">
						<a href="a" class=" hover:underline">
							Address{' '}
						</a>
					</li>
				</ul>
			</div>
			<div>
				<h2 class="mb-8 text-4xl font-semibold text-paper-100">Quick links</h2>
				<ul class="grid grid-cols-2 gap-y-6 text-2xl font-normal text-paper-400">
					<li class="">
						<a href="a" class="hover:underline"> Home </a>
					</li>
					<li class="">
						<a href="a" class="hover:underline"> Privacy policy </a>
					</li>
					<li class="">
						<a href="a" class="hover:underline"> About us </a>
					</li>
					<li class="">
						<a href="a" class="hover:underline"> Cookie policy </a>
					</li>
					<li class="md:col-span-2">
						<a href="a" class="hover:underline"> Token </a>
					</li>
					<li class="">
						<a href="a" class="hover:underline"> Blogs </a>
					</li>
				</ul>
			</div>
			<div>
				<h2 class="mb-8 text-lg font-semibold text-paper-100">Join our community</h2>
				<ul class="grid grid-cols-4 gap-y-6">
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Linkedin.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Discord.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Twitter.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Instagram.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Youtube.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Twitch.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Tiktok.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
					<li class="">
						<a href="a" class="hover:underline">
							<img
								src="/img/Facebook.png"
								alt=""
								class="h-[60px] w-[60px] object-cover"
								crossorigin="anonymous"
							/>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>
